services:
    anivt:
        image: ghcr.io/trzynastek/anivt:latest
        container_name: anivt
        ports:
            - 7980:7980
        volumes:
            - ./storage/mkv:/anivt/mkv
            - ./storage/mp4:/anivt/public/mp4
            - ./logs:/anivt/logs
            - ./configs:/anivt/configs
        environment:
            ANILIST_REDIRECT: '${ANILIST_REDIRECT}'
            ANILIST_CID: '${ANILIST_CID}'
            ANILIST_SECRET: '${ANILIST_SECRET}'
        # Intel iGPU passthrough for Quicksync support
        # devices:
        #   - /dev/dri:/dev/dri
        # group_add:
        #   - "103"
