services:
    anivt:
        image: anivt
        container_name: anivt
        ports:
            - 7980:7980
        volumes:
            - ./storage/mkv:/anivt/mkv
            - ./storage/mp4:/anivt/public/mp4
            - ./logs:/anivt/logs
            - ./configs:/anivt/configs
